### PR TITLE
[FEAT] add french language

### LINKED ISSUE #2263: [Feature]: add fr (french) language
### 功能概述 | Describe the feature

Hi! I'm enthusiast about Waline (and even implemented it on my website), but since I'm still learning web dev without being a dev and making things on my side, I don't really know how to make PR lol

But at least I know how the fr.ts file should look like, and I translated it :

/* fr.ts */

import { generateLocale } from './generate.js';

export default generateLocale([
  "Pseudo",
  "Le pseudo ne peut pas faire moins de 3 octets.",
  "E-mail",
  "Veuillez confirmer votre adresse e-mail.",
  "Site Web",
  "Optionnel",
  "Commentez ici...",
  "Aucun commentaire pour l'instant.",
  "Envoyer",
  "J'aime",
  "Annuler le j'aime",
  "Répondre",
  "Annuler la réponse",
  "Commentaires",
  "Actualiser",
  "Charger plus...",
  "Aperçu",
  "Emoji",
  "Télécharger une image",
  "Il y a quelques secondes",
  "Il y a quelques minutes",
  "Il y a quelques heures",
  "Il y a quelques jours",
  "À l'instant",
  "Téléchargement en cours",
  "Connexion",
  "Déconnexion",
  "Admin",
  "Épinglé",
  "Mots",
  "Veuillez saisir des commentaires entre $0 et $1 mots !\n Nombre actuel de mots : $2",
  "Anonyme",
  "Nains",
  "Hobbits",
  "Ents",
  "Mages",
  "Elfes",
  "Maïar",
  "GIF",
  "Rechercher un GIF",
  "Profil",
  "Approuvé",
  "En attente",
  "Indésirable",
  "Détacher",
  "Le plus ancien",
  "Dernier",
  "Le plus populaire",
  "Qu'en pensez-vous ?"
]);

If someone from the admins can add it, me and all the french users will be grateful forever! Thank you :)

---
### 功能概述 | Describe the feature

Hi! I'm enthusiastic about Waline (and even implemented it on my website), but since I'm still learning web dev without being a dev and doing things on my side, I don't really know how to make PR lol

But at least I know how the fr.ts file should look like, and I translated it:

/* fr.ts */

import { generateLocale } from './generate.js';

export default generateLocale([
  "Pseudo",
  "The nickname cannot be less than 3 bytes.",
  "E-mail",
  "Please confirm your email address.",
  "Website",
  "Optional",
  "Comment here...",
  "No comments yet.",
  "Send",
  "I like",
  “Unlike”,
  "Answer",
  "Cancel reply",
  "Comments",
  "Refresh",
  "Load more...",
  "Preview",
  "Emoji",
  "Upload an image",
  "A few seconds ago",
  "A few minutes ago",
  "A few hours ago",
  "A few days ago",
  "Just now",
  "Downloading",
  "Connection",
  "Disconnect",
  "Admin",
  "Pin",
  "Words",
  "Please enter comments between $0 and $1 words!\nCurrent word count: $2",
  "Anonymous",
  "Dwarves",
  "Hobbits",
  "Ents",
  "Magi",
  "Elves",
  “Maïar”,
  "GIF",
  "Search for a GIF",
  "Profile",
  "Approved",
  "On hold",
  "Undesirable",
  "Detach",
  "The oldest",
  "Last",
  "The most popular",
  "What do you think ?"
]);

If someone from the admins can add it, me and all the French users will be grateful forever! Thank you :)

### PR DESCRIPTION
**Pull request by lizheming**
close #2263 when pr closed

### CODE REVIEW

**Comment by lizheming** [comment]
@Mister-Hope 为什么关闭了这个 PR 呀？

**Comment by lizheming** [comment]
哦哦，看到了，你自己加上了，忽略我~

**Comment by PxlSyl** [comment]
Hi, first, thank you a lot for your reactivity! I tried to change the language in my app, and even switched to the v3 alpha version for the client package (with next.js). Implemented everything, even the pageview counter with some custom code :)

But for now, seems like fr is still not recognized in the package... I saw that a check were unsucessfull, maybe it's related to this?

**Comment by Mister-Hope** [comment]
Can you provide the output of `navigator.languages` in your console?

image

**Comment by PxlSyl** [comment]
I'm in France, here's the output : 
navlanguages

So I think you're right!

Not related, but just for you to know, I also get this warning : 
vuewarning

**Comment by PxlSyl** [comment]
Hi! Just updated to the latest release, and now it works, thank you a lot!

I now plan to write an article about how to implement waline with the templates I made :)

P.S.: Just a little improvment could be the updating of the typing file to show that's "fr" is available in the "lang" options

**Comment by lizheming** [comment]
@PxlSyl done for doc and typing https://github.com/walinejs/waline/commit/887d420b666511a5f6f563c1f1148e1bced2b8a7 https://github.com/walinejs/waline/commit/2895891ffe5efaaa00f614f659648694a23785e9

**Pull request closed without merging**
