### PR TITLE
修改模板链接为新模板

### PR DESCRIPTION
**Pull request by wsndshx**
原先的模板链接railway已经不再支持, 因此按照旧模板的内容创建了一个可用的新模板

### CODE REVIEW

**Comment by ilovefreesw** [comment]
The railway template link on the waline website https://waline.js.org/en/guide/deploy/railway.html  again stopped working.
image

**Comment by lizheming** [comment]
@ilovefreesw Thanks for the feedback, the link has been updated now, you can try again

**Comment by ilovefreesw** [comment]
Great. Btw can we use remote MySQL instead of Postgres in Railway setup?

**Comment by lizheming** [comment]
@ilovefreesw https://waline.js.org/en/guide/deploy/railway.html#how-to-modify-environment-variables yeah~ just modify env with MySQL

**Pull request merged**
