### PR TITLE
Create new translation for pt-BR

### PR DESCRIPTION
**Pull request by dannyloxavier**
Portuguese-Brazilian

### CODE REVIEW

**Review by lizheming — APPROVED** [review]

**Comment by dannyloxavier** [comment]
Sorry, thought it ended after approval.

**Comment by lizheming** [comment]
@dannyloxavier Sorry, I just approved it and have not merged yet. If you not mind, I'll copy your translation into project and publish it then you can enjoy your translation online.

**Comment by dannyloxavier** [comment]
Please, do it. The 'reopen' button isn't working.

**Comment by dannyloxavier** [comment]
Thank you.

**Pull request closed without merging**
