### PR TITLE
feat(client): support more accessibility for client components

### PR DESCRIPTION
**Pull request by cworld1**
As astro shows, it has a terrible accessibility.

image

These code can improve it.

### CODE REVIEW

**Review by lizheming — DISMISSED** [review]

**Comment by cworld1** [comment]
Er... a week has gone through

**Comment by Mister-Hope** [comment]
1. your pr is a terrible one for any eye impaired people.  Visual impaired people  DONOT need to upload images and DONOT need to read the avatars as nick name to prevent they heard the nickname **twice**.

The valid fix should be hiding the upload a button and giving the avatar image and empty alt.

So I will open a new one when I **have time**.  


2. Open source contributors can be busy in real life.  And I am mad at the situation in my real life now.   I am busy with my postgraduate thesis, and my 87 years old gradma just fall down last week and have to be take cared 24h.  Stop pushing any open source contributors unless you pay them as a sponsor

**Review by Mister-Hope — CHANGES_REQUESTED** [review]
The correct fix is already mentioned in comment above

**Comment by cworld1** [comment]
Sorry to hear that... But I reminded after a week just because a developer forgot to check the pr list and my pr was processed half a year later.

To prevent this from happening, I made what I thought was a friendly reminder, nothing more. I'm sorry if my wording misunderstood you.

I'll soon create a new pr as possible.

**Pull request closed without merging**
