### PR TITLE
fix(client): fix math match

### PR DESCRIPTION
**Pull request by Eumeryx**
修复以下问题：
1. 行内公式无法识别 `$\sqrt{x}$` 等以符号开头 和结尾的内容。
2. 连续的两个行间公式必须空出三行以 `'$$\n\n\n\n$$'` 为间隔，无法空一行以 `'$$\n\n$$'` 为间隔。
3. 当 `2` 发生时如 `‘$$y$$’` 等里面的 `'$y$'` 会被识别为行内公式。
4. 行间公式内无法换行。

此修改会引入一个新的行为：
* `'\n$$'` 和 `'$$\n'` 间的所有字符将被视为 tex

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Same problem with the earier PR, could you add some test files? (Especially the one works now)

**Comment by Mister-Hope** [comment]
Wait, I remenber that you are not familiar with jest right?

I will open a new branch and add some test for you.😀 Please wait

**Comment by Eumeryx** [comment]
> Wait, I remenber that you are not familiar with jest right?
> 
> I will open a new branch and add some test for you.😀 Please wait

是的，这是我第一次使用，你可以给我一些相关的提示吗？

**Comment by Mister-Hope** [comment]
Hold on, I will comit what I just did, you are able to complete it by adding more tests I think. The existing one can be good examples.

**Comment by Mister-Hope** [comment]
See the `client-math` branch, please merge it to the mathRegExp branch in your repository, and finish the rest part of the test.

**Comment by Eumeryx** [comment]
> See the `client-math` branch, please merge it to the mathRegExp branch in your repository, and finish the rest part of the test.
> 
> https://github.com/walinejs/waline/blob/485c49c10b112066419b0b922fe8d5dbd50cf6f4/packages/client/__tests__/math.spec.ts#L3-L57

OK, 我去学习一下。

**Comment by Mister-Hope** [comment]
> > See the `client-math` branch, please merge it to the mathRegExp branch in your repository, and finish the rest part of the test.
> > 
> > https://github.com/walinejs/waline/blob/485c49c10b112066419b0b922fe8d5dbd50cf6f4/packages/client/__tests__/math.spec.ts#L3-L57
> 
> OK, 我去学习一下。


其实你不用学，你只需要照葫芦画瓢往里面加新的测试样例就行。然后你可以添加一些目前暂时不能通过（也就是解析错误的案例）但是要以 `it.skip(` 开头而不是 `it(` 这样我们也能记录哪些案例是不能通过的。

选取一些有代表性的作为单元测试项目即可。就是用尽可能少的条目覆盖尽可能多的情况。

**Comment by Mister-Hope** [comment]
Just as a reminder, the last test unit test expected value is wrong, the `<p>` tag should not exist because it's not passed to `marked` yet, you should fix that. I commit that in a hurry.

**Comment by Mister-Hope** [comment]
LGTM, thanks for contributing waline! ❤

**Pull request merged**
