### PR TITLE
Add email notification defaults, templates to docs

### PR DESCRIPTION
**Pull request by stevygee**
Was setting up my email notifications using Mailjet and came across some issues, where the documentation could have been more clear.

### CODE REVIEW

**Review by lizheming — APPROVED** [review]

**Comment by lizheming** [comment]
Thanks for your PR. The default mail notification template is chinese language right now, I'll translate it to english version asap.

**Comment by stevygee** [comment]
> Thanks for your PR. The default mail notification template is chinese language right now, I'll translate it to english version asap.

Thanks! I can share my translation, if you want?

**Comment by lizheming** [comment]
> Thanks! I can share my translation, if you want?

Great, please share it!

**Comment by lizheming** [comment]
@stevygee You can also define them in the `index.js` https://waline.js.org/en/reference/server.html#mailsubject

**Comment by stevygee** [comment]
@lizheming Here you go, this is how I translated the templates: https://pastebin.com/FiBsQFGA

**Comment by lizheming** [comment]
@stevygee Got it! Thank you very much~

**Pull request merged**
