### PR TITLE
[FEATURE] Uniform avatar configure by AVATAR_PROXY

### LINKED ISSUE #525: Avatar 配置优化
目前前端 Gravatar 配置是需要在前端进行配置的，随着使用头像服务的场景越来越多，在各个使用的地方配置代理服务显得很麻烦。需要优化成统一由接口层返回 avatar 头像地址，头像代理服务配置也统一走服务端配置。

### PR DESCRIPTION
**Pull request by lizheming**
close #525 when pr closed.

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Some questions:

1. Is client now just need to use the link directly and all avatar settings in client won't have any effects?
2. Do we need to try parsing the returned link and making avatar settings in client workable? (e.g.: avatarCDN)

**Comment by lizheming** [comment]
> Some questions:
> 
> 1. Is client now just need to use the link directly?
> 2. Do we need to try parsing the returned link and making avatar settings in client workable? (e.g.: avatarCDN)

1. Yes 
2. md5 mail will also return and all client gravatar configuration like `avatarCDN` and `avatar` works well right now. But I have update documentation that `avatarCDN`, `avatar` and `avatarForce` is deprecated and will remove in next major version.

**Comment by Mister-Hope** [comment]
Since the client is an instance now and can be updated, I will need extra function to detect if the current avatar config is the same as default config.

I will try to make this change graceful.

**Comment by Mister-Hope** [comment]
`avatarForce` can still be supported on the client, do we need to keep it?

**Comment by lizheming** [comment]
@Mister-Hope `avatarForce` also will be deprecated.

**Comment by Mister-Hope** [comment]
So we are actually removing the "force fetch" feature?

**Comment by lizheming** [comment]
@Mister-Hope All avatar configuration will move to https://github.com/waline/porter and custom it If they want. And  https://github.com/waline/porter has no cache right now, so `avatarForce` is no needed.

**Comment by Mister-Hope** [comment]
Got it, so I just need to detect if user are implict setting any avatar options, and use the old logic, otherwise just using the `avatar` property on comment right?

**Comment by lizheming** [comment]
@Mister-Hope Yes, you're right. I think client has comment avatar field detection feature already and do not need  any more work about it, because login user comment data will export avatar field.

**Comment by lizheming** [comment]
@Mister-Hope I'll update minor version and add some description in the changelog.

**Comment by Mister-Hope** [comment]
I am not looking forward to raise a major version, as I am planing to drop some support of old filelds in Valine when raising to V2. (Such as the Chinglish `langMode`)

**Comment by lizheming** [comment]
@Mister-Hope OK, so we can create v2 branch and merge those break feature into it and release v2 beta version.

**Comment by Mister-Hope** [comment]
> BTW, currently is there a way for me to detect if a user is a login user?

Is there a way to keep this? If so I can still support it without making breakding changes.

**Comment by lizheming** [comment]
@lizheming a comment data has `type` field is posted by login user.

**Pull request merged**
