### PR TITLE
[FEAT] Default language switch

### PR DESCRIPTION
**Pull request by lizheming**
- use `navigator.language` as default lang option value 
- switch to `en-US` as default language

### CODE REVIEW

**Comment by Mister-Hope** [comment]
I am afraid this will break ssr usage as there is no navigator in ssr.

**Comment by lizheming** [comment]
I remember the official documentation site used ssr with waline. It works well, so may it not a confused point?
btw, I think `@waline/client` should be initialized in componentDidMount life cycle, so it will run in the browser mode.

**Comment by Mister-Hope** [comment]
It is, the offfcial docs always passes in current language.

**Comment by lizheming** [comment]
I have try to remove lang configure for official site and can reproduce the problem. But I have no idea to fix it, maybe you can fix it after you are recovery.

And I have some confuse about this. All place which `navigator.language` used also have `path` parameter which default value set as `location.pathname`. `location` is also a browser variable, why it works well before?

**Comment by Mister-Hope** [comment]
Because path is designed to be required when rending ssr😅 but O don't think lang should.

It's totally reasonable for an SSR rendering to force path being declared.

To solve this, just write:

```
typeof navigator === 'undefined'? 'en-US': navigator.ua.language
```

**Comment by Mister-Hope** [comment]
Because path is designed to be required when rending ssr😅 but O don't think lang should.

It's totally reasonable for an  SSG or SSR to force path being declared.

To solve this, just write:

```
typeof navigator === 'undefined'? 'en-US': navigator.ua.language
```

**Pull request merged**
