### PR TITLE
fix(hexo-next): emoji default value

### PR DESCRIPTION
**Pull request by leirock**
I use `[]` to envelope the value of `emoji`. Without `[]`, there will be an error if users don't set the value of `emoji` in `config.yml`.

### CODE REVIEW

**Comment by Mister-Hope** [comment]
> I use `[]` to envelope the value of `emoji`. 

I disagree that as this is wiping default weibo emoji

> Without `[]`, there will be an error if users don't set the value of `emoji` in `config.yml`.

Any error details? `@waline/client` should work fine when calling with `emoji: []` directly. So I actually don't understand why `emoji: []` don't work, you may try locally, to make sure that it's working in your env, but after wraping by hexo it's not.

**Comment by leirock** [comment]
## 1. Without `[]` in `default.yaml`

default.yaml
```yml
  emoji:
    # - https://unpkg.com/@waline/emojis@1.0.1/weibo
    # - https://unpkg.com/@waline/emojis@1.0.1/alus
    # - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    # - https://unpkg.com/@waline/emojis@1.0.1/qq
    # - https://unpkg.com/@waline/emojis@1.0.1/tieba
    # - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
```

If the user sets `emoji: []` in Hexo root `config.yml` to turn off emoji, yes, everything goes fine. 

But if not, for example, in Hexo root `config.yml` (no other custom config)
```yml
waline:
  enable: true
  serverURL: https://cmt.pinlyu.com
```

Then the value of `emoji` in exported waline config is `"emoji":null`

And no comment editor box
image

And error msg in console
image

## 2. With `[]` in  `default.yaml` like this PR

Whether users set the value of `emoji` in Hexo root `config.yml` will not lead to an error. 

If the user doesn't set the value of `emoji` in Hexo root `config.yml`, then the exported waline config is `"emoji":[]` (from `default.yaml`). The button of emoji will be hidden.

**Comment by Mister-Hope** [comment]
@leirock I mean comment that key, a key without value equals up key: null in y’all, (sign)

**Comment by leirock** [comment]
> @leirock I mean comment that key, a key without value equals with key: null in yaml, (sign).

I don't quite understand what you mean. Anyway, you can edit my PR to make it better.

**Comment by Mister-Hope** [comment]
```yml

# emoji:
    # - https://unpkg.com/@waline/emojis@1.0.1/weibo
    # - https://unpkg.com/@waline/emojis@1.0.1/alus
    # - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    # - https://unpkg.com/@waline/emojis@1.0.1/qq
    # - https://unpkg.com/@waline/emojis@1.0.1/tieba
    # - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji

```

**Comment by leirock** [comment]
> ```yaml
> # emoji:
>     # - https://unpkg.com/@waline/emojis@1.0.1/weibo
>     # - https://unpkg.com/@waline/emojis@1.0.1/alus
>     # - https://unpkg.com/@waline/emojis@1.0.1/bilibili
>     # - https://unpkg.com/@waline/emojis@1.0.1/qq
>     # - https://unpkg.com/@waline/emojis@1.0.1/tieba
>     # - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
> ```

OK, I see.

**Comment by Mister-Hope** [comment]
Btw, what's the original issue again?

**Comment by Mister-Hope** [comment]
So, if you do understand yaml incorrectly, there should be no issue here

**Comment by leirock** [comment]
Just tried, but the emoji button cannot be hidden if all are commented. 

The exported config is 
```
{"lang":"zh-CN","enable":true,"serverURL":"https://cmt.pinlyu.com","cssUrl":"//unpkg.com/@waline/client@v2/dist/waline.css","locale":{"placeholder":"Welcome to comment"},"commentCount":true,"pageview":false,"el":"#waline","comment":true,"libUrl":"//unpkg.com/@waline/client@v2/dist/waline.js","path":"/post/60/"}
```

**Comment by leirock** [comment]
without any emoji value in the config, the emoji button will not be hidden.

**Comment by Mister-Hope** [comment]
?Didn’t the docs told you that emoji has a default value? You are supposed to set `emoji: []` in your own config to tell waline you do not want the default weibo emoji. (And we will support `emoji : false` In next version)

so what’s the problem here?

**Comment by Mister-Hope** [comment]
If there is really something we can do, maybe is to comment every unneeded options in default.yml, as waline actually don’t need them.

**Comment by Mister-Hope** [comment]
Closing as this is fixed in main, appeciate for your feedback.

**Pull request closed without merging**
