### PR TITLE
feat: add Russian language

### PR DESCRIPTION
**Pull request by aw83**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Could you please unify the lang code to `language-contry` format, maybe `ru-RU`? (Not sure)

**Comment by lizheming** [comment]
@Mister-Hope I think use `ru` the language code only is ok for this case~ and it's same configure which I have ref other oss like remark42.

**Comment by lizheming** [comment]
`@waline/client@1.6.0` has published, thank you for your work!

**Comment by Mister-Hope** [comment]
image

But it would be better to add support for `ru-RU`.

**Comment by lizheming** [comment]
yes, I'm agree with you.

**Comment by aw83** [comment]
I filed another PR #849. As suggested by @Mister-Hope https://github.com/walinejs/waline/pull/848#issuecomment-1059764300. So I added `ru-RU` and `ru-ru`.

**Pull request merged**
